### ISSUE TITLE
What license for this code?

### ISSUE THREAD

**Issue by sidan5** [bgayman/Duck-Hunt-Sprite-Kit#1]
Is it MIT?

**Comment by bgayman** [comment]
Feel free to use the code. I would not use the assets for commercial purposes though. I'm not sure of their copyright status, but they are widely available on the internet.

On Oct 29, 2015, at 08:55 AM, Idan notifications@github.com wrote:

Is it MIT?

**Comment by sidan5** [comment]
Not going to use the assets. Although it's a cool retro :)

Should I push my fixes or it is a dead repo?
